spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    host: 127.0.0.1
    database: sdemo
    port: 3306
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 


      
      
      
      
      