spring:
  profiles:
    active: '@profiles.active@'
  application:
    name: sdemo
  messages:
    basename: i18n/messages
  redis:
    host: 10.103.237.33
    port: 6379
    key-prefix: sdemo
    lock-expire-time: 30 #分钟,分布式锁过期时间
    jedis:
      pool:
        max-active: 300
        time-between-eviction-runs: 60s
        min-idle: 8
  datasource:
    host: 127.0.0.1
    database: sdemo
    port: 3306
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    format: 
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1024MB
  mail:
    host: smtp.mxhichina.com
    username: rdd@lenovoedu.com
    password: 1234Qwer
    default-encoding: UTF-8
    protocol: smtp
    from: rdd@lenovoedu.com
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  
server:
  port: 8080
  servlet: 
    context-path: /sdemo

logging:
  file:
    path: 
    name: /logs/sdemo/sdemo.log
    max-history: 30
  level:
    com.suo.sdemo: DEBUG
shiro:
  session:
    timeout: 7200000   #2*60*60*1000 两小时
swagger:
  enable: true
  
cors:
  allow-origin: "*"
  allow-credentials: false
  allow-methods: "*"
  allow-headers: "*"

#文件存储地址
file:
  storage-path: /data/sdemo/files #上传文件父路径
